// <auto-generated />
using HTB.Strategy.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HTB.Strategy.Migrations.Migrations
{
    [DbContext(typeof(StrategyReadonlyDbContext))]
    [Migration("20260629211846_AddStrategyRuleSets")]
    partial class AddStrategyRuleSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("strategy")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HTB.Strategy.Shared.Domain.StrategyDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string[]>("Exchanges")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("exchanges");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string[]>("Symbols")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("symbols");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<short[]>("Timeframes")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("timeframes");

                    b.Property<int>("WarmupBars")
                        .HasColumnType("integer")
                        .HasColumnName("warmup_bars");

                    b.HasKey("Id", "Version");

                    b.ToTable("strategy_definitions", "strategy");
                });

            modelBuilder.Entity("HTB.Strategy.Shared.Persistence.StrategyRuleSetRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.HasKey("Id", "Version");

                    b.ToTable("strategy_rule_sets", "strategy");
                });

            modelBuilder.Entity("HTB.Strategy.Shared.Persistence.StrategyRuleSetRow", b =>
                {
                    b.HasOne("HTB.Strategy.Shared.Domain.StrategyDefinition", "Definition")
                        .WithOne("RuleSet")
                        .HasForeignKey("HTB.Strategy.Shared.Persistence.StrategyRuleSetRow", "Id", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("HTB.Strategy.Shared.Domain.StrategyDefinition", b =>
                {
                    b.Navigation("RuleSet");
                });
#pragma warning restore 612, 618
        }
    }
}
