// <auto-generated />
using System;
using HTB.Shared.Strategy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HTB.Strategy.Migrations.Migrations
{
    [DbContext(typeof(StrategyReadonlyDbContext))]
    partial class StrategyReadonlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("strategy")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HTB.Shared.Strategy.Persistence.StrategyVersionRecord", b =>
                {
                    b.Property<string>("StrategyId")
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MetaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RulesHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rules_hash");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rules_json");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema_version");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("Timeframe")
                        .HasColumnType("smallint")
                        .HasColumnName("timeframe");

                    b.Property<int>("WarmupBars")
                        .HasColumnType("integer")
                        .HasColumnName("warmup_bars");

                    b.HasKey("StrategyId", "VersionNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_strategy_versions_status");

                    b.ToTable("strategy_versions", "strategy");
                });
#pragma warning restore 612, 618
        }
    }
}
