// <auto-generated />
using System;
using HTB.Shared.MarketData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HTB.MarketData.Migrations.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    partial class MarketDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HTB.Shared.MarketData.Candle", b =>
                {
                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_id");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer")
                        .HasColumnName("symbol_id");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint")
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_time");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("high");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("open");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("quote_volume");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_count");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("ExchangeId", "SymbolId", "Interval", "OpenTime");

                    b.HasIndex("SymbolId", "Interval", "OpenTime")
                        .HasDatabaseName("ix_candles_symbol_interval_time");

                    b.ToTable("candles", (string)null);
                });

            modelBuilder.Entity("HTB.Shared.MarketData.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("exchanges", (string)null);
                });

            modelBuilder.Entity("HTB.Shared.MarketData.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_asset");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_id");

                    b.Property<string>("ExchangeSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exchange_symbol");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_asset");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId", "ExchangeSymbol")
                        .IsUnique();

                    b.ToTable("symbols", (string)null);
                });

            modelBuilder.Entity("HTB.Shared.MarketData.Candle", b =>
                {
                    b.HasOne("HTB.Shared.MarketData.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HTB.Shared.MarketData.Symbol", b =>
                {
                    b.HasOne("HTB.Shared.MarketData.Exchange", null)
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
