// <auto-generated />
using System;
using HTB.MarketData.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HTB.MarketData.Migrations.Migrations
{
    [DbContext(typeof(MarketDataReadonlyDbContext))]
    partial class MarketDataReadonlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("marketdata")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HTB.MarketData.Shared.Domain.Candle", b =>
                {
                    b.Property<string>("Exchange")
                        .HasColumnType("text")
                        .HasColumnName("exchange_code");

                    b.Property<string>("Symbol")
                        .HasColumnType("text")
                        .HasColumnName("symbol_code");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint")
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_time");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("high");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("open");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("quote_volume");

                    b.Property<int>("TradeCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_count");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("Exchange", "Symbol", "Interval", "OpenTime");

                    b.HasIndex("Symbol", "Interval", "OpenTime")
                        .HasDatabaseName("ix_candles_symbol_interval_time");

                    b.ToTable("candles", "marketdata");
                });

            modelBuilder.Entity("HTB.MarketData.Shared.Domain.Exchange", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("exchanges", "marketdata");
                });

            modelBuilder.Entity("HTB.MarketData.Shared.Domain.Symbol", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_asset");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exchange_code");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_asset");

                    b.HasKey("Code");

                    b.HasIndex("Exchange", "Code")
                        .IsUnique();

                    b.ToTable("symbols", "marketdata");
                });

            modelBuilder.Entity("HTB.MarketData.Shared.Domain.Candle", b =>
                {
                    b.HasOne("HTB.MarketData.Shared.Domain.Exchange", null)
                        .WithMany()
                        .HasForeignKey("Exchange")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HTB.MarketData.Shared.Domain.Symbol", null)
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HTB.MarketData.Shared.Domain.Symbol", b =>
                {
                    b.HasOne("HTB.MarketData.Shared.Domain.Exchange", null)
                        .WithMany()
                        .HasForeignKey("Exchange")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
